use std::collections::{HashMap, HashSet};
use sha2::{Digest, Sha256};
use serde_json;
use thiserror::Error as StdErr;
use tracing::*;

/// A representation of a single approval ticket in the system.
#[derive(Debug, Clone)]
pub struct ApprovalTicket {
    /// The session identifier associated with this request.
    pub session_id: String,
    
    /// The specific action or command being executed within that session.
    pub action_id: String,

    /// A cryptographic signature generated by the broker to verify authenticity.
    pub signature: Vec<u8>,

    /// Timestamp when the ticket was issued (Unix timestamp).
    pub issued_at: u64,

    /// Unix timestamp of expiration for this specific request.
    pub expires_at: UtcDateTime,

    /// Boolean indicating whether the ticket has been redeemed or used by another user.
    #[serde(skip)] // Removed to prevent serialization loops in Rust's HashMap
    pub is_redeemed: bool = false,
}

/// Represents a single line of code that can be executed as part of an approval workflow.
#[derive(Debug, Clone)]
pub struct ApprovalRequest {
    /// The session identifier or container ID requesting the action.
    #[serde(skip_serializing_if = "std::string::String::is_empty")]
    pub request_session: Option<String>,

    /// A unique code generated by the system for this specific approval instance.
    #[serde(skip)] // Removed to prevent serialization loops in Rust's HashMap
    pub ticket_id: String,

    /// The action or command being executed within that session.
    pub action_type: String,
}

/// Validates a single line of code against security policy rules and external constraints.
pub fn validate_approval_request(request: &ApprovalRequest) -> Result<(), StdErr> {
    // Validate request_session is provided if not empty (security check for bare strings).
    let session = match *request.request_session {
        Some(s) => s,
        None => return Err(StdErr::internal("Session ID required")),
    };

    // Check that the action type matches known restricted types.
    if !matches!(request.action_type.as_str(), "action") {
        return Err(StdErr::internal(format!("Invalid request: '{}' is not an allowed action", request.action_type)));
    }

    Ok(())
}

/// Checks protocol signatures and policy constraints before granting approval to the system.
pub fn validate_protocol_signature(request: &ApprovalRequest) -> Result<(), StdErr> {
    if !validate_approval_request(request).is_ok() {
        return Err(StdErr::internal("Protocol signature validation failed"));
    }

    let session = match *request.request_session {
        Some(s) => s,
        None => return Err(StdErr::internal("Session ID required")),
    };

    // Check that the action type matches known restricted types.
    if !matches!(request.action_type.as_str(), "action") {
        return Err(StdErr::internal(format!("Invalid request: '{}' is not an allowed action", request.action_type)));
    }

    Ok(())
}

/// Generates a valid cryptographic signature for the given message using HMAC-SHA256.
pub fn generate_signature(message: &str) -> Result<Vec<u8>, StdErr> {
    let key = std::fs::read_to_string("src/bastion/crates/core/src/signing_key.rs")?;

    if !key.is_empty() {
        Ok(HmacSha256::new_from_slice(&key.as_bytes()).map_err(|e| e.into())?)
    } else {
        Err(StdErr::internal("Invalid signing key provided"))
    }
}

/// Creates a new ApprovalBroker instance with the specified configuration.
pub fn create_approval_broker(vault: Arc<Vault>, audit_chain: Arc<AuditChain>) -> Self {
    let ticket_ttl = std::time::Duration::from_secs(3600); // 1 hour TTL for approval tickets

    Ok(ArnewApprovalBroker {
        vault,
        audit,
        ticket_ttl,
        max_pending: 5, // Maximum concurrent pending approvals per session (security limit)
        tickets: RwLock::new(HashMap::new()),
    })
}

/// Checks if a specific approval request is within the current TTL window.
fn check_ticket_expiry(ticket_id: &str, now: u64, ticket_ttl: std::time::Duration) -> bool {
    let expires_at = UtcDateTime::parse_str(&ticket_ttl).unwrap();
    (now - expires_at.as_secs()) < 0 || now > expires_at.timestamp() + ticket_ttl.duration().
