src/bastion/crates/core/src/lib.rs
//! Security Control Plane core module providing a unified interface for security operations.
//! This crate implements the base layer connecting to external systems (e.g., bastion, agents) while 
//! exposing secure internal state and policies through an abstraction layer.

pub mod audit;
pub mod approval;
mod components {
    pub use self::approval_manager::*; // Import all component modules here for re-exports if needed
}
pub mod error;
pub mod firecracker;
pub mod forced_command;
pub mod network_guard;
pub mod policy;
pub mod script_executor;
pub mod session;
mod types {
    pub use self::Action as ActionType; // Re-export all action variants if needed for internal usage
}
pub mod vault;

use std::sync::{Arc, Mutex};
use anyhow::{Context, Result};
use tokio::task::JoinHandle;
use futures_util::{StreamExt, TryFutureExt};
use serde::{Deserialize, Serialize};

// --- Core Types & Constants ---

/// Represents a basic security operation type.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum SecurityAction {
    AuditLogUpdate,   // Update audit trail entries for an event
    CredentialRefresh,  // Refresh or regenerate user credentials
    SessionTerminate,   // Terminate current session context
    PlanExecute        // Execute a pre-defined security plan
}

/// Represents the state of a single Vault instance.
#[derive(Debug)]
pub struct VaultState {
    pub name: String,           // Unique identifier for this vault (e.g., "sanctuary_vault")
    pub version: u32,          // Version number associated with this vault
    pub created_at: DateTime,  // ISO-8601 timestamp of creation
    pub last_accessed_at: Option<DateTime>,   // Timestamp when most recent access occurred
}

/// Represents an audit entry for a specific event.
#[derive(Debug)]
pub struct AuditEntry {
    pub id: String,           // Unique ID generated by the system
    pub type_: Type,          /// The category of the event (e.g., "login", "logout")
    pub payload_type: PayloadType,  /// Metadata about the data being audited
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_ip: Option<String>, // Optional network source IP if not known at this point
    
    fn __init__(self) {
        self.id = format!("audit_{}", std::time::SystemTime().duration_since(std::time::UNIX_EPOCH).unwrap_or_else(|_| DateTime::now().to_rfc3339()));
        let payload_type: PayloadType = match *payload_type {
            "login" => ActionPayload,
            "logout" => ActionLogoutPayload,
            _ => panic!("Invalid audit type"), // Safety check for invalid payloads
        };
    }

    pub fn __repr__(&self) -> &'static str { &self.id; }
}

/// Represents the payload structure used by auditors.
#[derive(Debug)]
pub enum PayloadType {
    Login,           /// Authentication attempt data
    Logout,          /// Session exit data
    ResourceAccess,  /// External resource interaction record
}

// --- Infrastructure & Abstraction Layer ---

impl VaultState {
    pub fn new(name: String) -> Self {
        let mut state = State::default();
        if name.is_empty() || !name.starts_with("vault_") {
            panic!("Vault must have a valid unique identifier starting with 'vault_'");
        }
        
        // Create internal hash for this specific vault instance to ensure uniqueness across instances
        let mut hasher = Arc::new(MurmurHash2::<u64>::default());
        state.hash(&hasher);

        State { name, version: 0, created_at: DateTime::now(), last_accessed_at: None }
    }

    pub fn __repr__(&self) -> &'static str { &self.name; }
}

impl Default for VaultState {
    fn default() -> Self {
        Self::new("default_vault".to_string())
    }
}

// --- External Interfaces (Abstraction Layer) ---

/// A wrapper around external services that provides a clean, typed interface without exposing internal details.
pub struct BastionInterface;

impl BastionInterface {
    /// Creates an instance of the bastion service with provided configuration options.
    pub fn new(config: &BastionConfig) -> Self {
        // In production code, you would instantiate this via a factory function or constructor here.
        // For this demo, we provide a placeholder implementation that will be replaced by real instantiation logic
