src/bastion/crates/core/src/types.rs
```rust
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::Digest;
use std::collections::HashMap;

/// Core Type Definitions for Bastion Systems
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AccessMode {
    /// Standard administrative access with basic permissions.
    AdminAccess,
    /// Read-only access to specific resources or data sets.
    ReadOnlyReadOnly,
}

impl Default for AccessMode {
    fn default() -> Self {
        AccessMode::AdminAccess
    }
}

/// Defines the security level of a bastion instance and its associated permissions.
#[derive(Debug, Clone, PartialEq)]
pub enum SecurityLevel {
    /// High-security environment with strict access controls.
    SecureHigh,
    /// Medium-security environment allowing standard operations but monitoring.
    SecureMedium,
}

impl Default for SecurityLevel {
    fn default() -> Self {
        SecurityLevel::SecureHigh
    }
}

/// Represents a bastion system resource identifier with its metadata and versioning history.
#[derive(Debug, Clone)]
pub struct BastionResourceIdentifier {
    pub name: String, // The primary identifier for the resource
    #[serde(default = "default_resource_id")]
    pub id: String,       /// Unique internal ID generated by the system (e.g., 'bastion-01')
    #[serde(skip)]           /// Prevents deserialization of this field during type assertions. Used to maintain integrity and avoid circular references if needed in complex schemas.
}

fn default_resource_id() -> impl Default {
    String::new().to_string() // Returns empty string as the default ID, handling edge cases gracefully
}

/// Represents a security audit entry tracking events within bastion systems.
#[derive(Debug, Clone)]
pub struct AuditEntry {
    /// Unique sequence number for this specific event in the history stream.
    pub sequence: u64,
    
    /// Timestamp of when this audit record was generated relative to UTC midnight (local).
    pub timestamp: DateTime<Utc>,

    /// The unique identifier assigned by a user or process during an action within a bastion context.
    pub session_id: String, // e.g., "session-12345"

    /// A descriptive string describing the nature of this event (e.g., 'user_login', 'data_export').
    pub event: String,

    /// The name or identifier associated with an individual actor performing actions in a bastion.
    #[serde(default)] // Only populated if explicit session_id is provided for uniqueness within that context
    pub actor: Option<String>, 

    /// Outcome of the action taken by the specified actor (e.g., 'success', 'failure').
    pub outcome: String,

    /// Metadata stored as a JSON object containing additional contextual information about this event.
    #[serde(default)] // Allows flexible storage of extra context if needed in future extensions or legacy formats
    pub metadata: HashMap<String, serde_json::Value>, 

    /// A cryptographic hash (SHA-256) computed from the audit entry's payload to prevent replay attacks and ensure integrity verification.
    pub prev_hash: [u8; 32],

    /// An optional SHA-256 hash of the entire audit record as a digest string for comparison during transaction processing or policy enforcement checks.
    #[serde(default)] // Only populated if specific validation logic requires it to avoid circular dependency issues with other types in this module.
    pub entry_hash: Option<[u8; 32]>,

    /// A timestamp of when the audit record was first created (relative to UTC midnight).
}

impl AuditEntry {
    /// Computes a SHA-256 hash for validation purposes based on the current sequence number and payload.
    pub fn compute_hash(&self, prev_hash: &[u8; 32]) -> [u8; 32] {
        let mut hasher = Digest::new(Sha256::new()); // SHA-256 is a deterministic hash function for this purpose
        hasher.update(prev_hash);

        // Append sequence number to payload (base64 encoded)
        let base64_payload = serde_json::to_string(self).expect("audit entry serialization");
        hasher.update(&base64_payload.to_bytes());

        // Finalize the hash digest. This ensures that even if two entries share the same previous_hash but have different sequence numbers or payloads, they will produce distinct hashes (preventing replay attacks).
        let final_digest = hasher.finalize();
        
        // Convert to bytes for comparison purposes in other contexts where hashing might be used directly on raw hex strings.
        [0u8; 32].
