src/__init__.py
"""
Security Control Plane Package v1.0
A robust framework for secure digital authentication and session management within a bastion environment.
Designed to be self-contained with no external dependencies beyond Python's standard library.
"""

# ============================================================================
# EXPLICIT EXPORTS FOR CLEAN MODULE INTERFACE (as per __init__.py requirements)
# ============================================================================

__all__ = [
    # Core Security Logic
    "security_control_plane",  # The main module entry point for the control plane logic
    "core_security_manager",   # Handles protocol validation, token binding, session expiration
    
    # CLI Tools (via a wrapper function in core security manager)
    "cli_secure_tls",           # Command: 'secure-tls' - Manages TLS/SSL and authentication tokens
    "cli_audit_log",            # Command: 'audit-log' - Generates structured audit logs for control-plane events

    # Session Management & Audit Tracing (via the core module)
    "session_manager",          # Handles session lifecycle, token binding expiration, and comprehensive auditing
]


# ============================================================================
# CORE SECURITY LOGIC MODULE
# Implements protocol validation, secure cipher suites, token binding/expiration enforcement,
# and audit logging for all control-plane events.
# ============================================================================

from typing import Optional, Dict, Any, List
import hashlib
import secrets
from dataclasses import dataclass, field
from enum import Enum


@dataclass(order=True)
class SessionState:
    """Represents the state of a single user session."""
    token_id: str  # Unique identifier for this specific auth token
    expires_at: Optional[float] = None      # Unix timestamp when token should be expired (None = permanent until revoked)
    is_revoked_by_admin: bool = False       # Boolean indicating if the admin has revoked this user
    last_activity_time: float = 0.0         # When the session was activated
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "token_id": self.token_id,
            "expires_at": self.expires_at,
            "is_revoked_by_admin": self.is_revoked_by_admin,
            "last_activity_time": self.last_activity_time,
        }


@dataclass(order=True)
class AuthEvent:
    """Represents a single event recorded during the security control plane."""
    id: str  # Unique ID for this log entry (auto-generated by session_manager)
    timestamp: float = field(default_factory=lambda time.time())
    level: str = "INFO"  # LOG, WARN, ERROR
    message: str = ""      # Human-readable description
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "timestamp": self.timestamp,
            "level": self.level,
            "message": self.message,
        }


class ProtocolStatus(Enum):
    """Represents the current state of the TLS/SSL connection."""
    UNSET = 0      # Not connected or unknown protocol version
    CONNECTED = 1   # Connection established with valid cipher suite
    INVALID_CIPHER = 2  # Invalid certificate chain, weak key size, etc.


class CipherSuite(Enum):
    """Supported encryption algorithms and ciphers."""
    TLS_AES_128_GCM_SHA256 = "TLS_AES_128_GCM_SHA256"      # Modern, secure cipher suite
    TLS_RSA_WITH_CHACHA20_POLY1305_SHA256 = "TLS_RSA_WITH_CHACHA20_POLY1305_SHA256"  # RSA + ChaCha20 (fallback)


class SecurityManager:
    """
    Core module for the security control plane.

    Responsibilities:
        - Validate TLS/SSL protocols and cipher suites
        - Enforce token expiration per session
        - Track audit logs of all events
        - Support CLI commands via a wrapper function
    """

    def __init__(self):
        self._events: List[AuthEvent] = []  # Global event log for auditing
        self._protocol_status: ProtocolStatus = ProtocolStatus.UNSET
        self._active_sessions: Dict[str, SessionState] = {}  # Map token_id -> session state

    def add_audit_event(
        self, 
        level: str = "INFO", 
        message: Optional[str] = None
    ) -> AuthEvent:
        """Add a new audit event to the global log."""
        if not isinstance(message, str):
            raise TypeError("Message must be a string")
        
        id_str = secrets.token_hex(16)  # Generate unique ID for this specific entry
        
        auth_event = AuthEvent(id=id_str, timestamp=time.time(),
