PROGRAM AbstractDataTypeGenerator
  TYPE-SET OF DEBTS = [DEBT_TYPE, DUE_DATE, AMOUNT]
  TYPE-SET OF PAYMENTS = [PAYMENT_ID, DATE, AMOUNT, STATUS]
  
  FUNCTION GET_DEBT_SUMMARY
    IMPORTS: DEBT_TYPES AS LIST.
    
    DEFINITIONS: 
      - DEFAULT_BENEFIT_AMOUNT   : LONG DOUBLE PRECISION := 100000.0F24; -- $100k base benefit
      - MINIMUM_FEE_RATE          : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)
    
    DEFINITIONS: 
      - TOTAL_BENEFIT : LONG DOUBLE PRECISION := 0.0F24; -- Accumulated benefit
      - REQUIRED_FEE   : LONG DOUBLE PRECISION := 0.0F24; -- Required monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)
    
    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE   : LONG DOUBLE PRECISION := .5E-3; -- 0.5% monthly fee
      
    FUNCTION GET_DEBT_SUMMARY(
      IN: DEBT_TYPES AS LIST OF TYPE-SET, 
      OUT: SUMMARY RECORDS AS LIST)

    IMPORTS: TOTAL_BENEFIT FROM ALL RECS.

    DEFINITIONS:
      - DEFAULT_FEE_RATE
