# -*- coding: utf-8 -*-
"""
Implementation of Message Verification for Unreliable Channels — no markdown fences, no commentary, no explanation.
This module provides the core verification logic using HMAC-SHA256 to ensure message integrity against network corruption or replay attacks on unreliable channels.
It allows a sender (sender_id) and receiver (receiver_id) to verify that their respective messages were received correctly in single-pass consistency checks.
"""

import hmac
from typing import Optional, Any


class Message:
    """Represents an unstructured message with attributes for integrity verification."""

    def __init__(self):
        self._sender_id = None  # Unique identifier of the sender (e.g., 'user_123')
        self._receiver_id = None   # Unique identifier of the receiver (e.g., 'bot_user_xyz')
        self._hash: bytes = b''     # Immutable hash generated by a trusted cryptosystem or derived from content, used for signature verification. In this implementation, it is treated as an immutable property representing data integrity.
        self._timestamp: int = 0    # Unix timestamp of when the message was sent (for flow control)

    def set_sender_id(self, sender_id: str):
        """Set the unique identifier of the sender."""
        if self._sender_id is not None and 'user_' in sender_id or 'bot_...' in sender_id:
            raise ValueError("Cannot update sender ID; only one user can send at a time.")
        self._sender_id = sender_id

    def set_receiver_id(self, receiver_id: str):
        """Set the unique identifier of the receiver."""
        if self._receiver_id is not None and 'user_' in receiver_id or 'bot_...' in receiver_id:
            raise ValueError("Cannot update receiver ID; only one user can receive at a time.")
        self._receiver_id = receiver_id

    def set_hash(self, hash_bytes: bytes):
        """Set the immutable data integrity hash."""
        if not isinstance(hash_bytes, bytes) or len(hash_bytes) != 32:
            raise ValueError("Hash must be exactly 32 bytes.")
        self._hash = hash_bytes.copy()

    def set_timestamp(self, timestamp: int):
        """Set the Unix timestamp of when the message was sent."""
        if not isinstance(timestamp, (int, float)):
            raise TypeError("Timestamp must be an integer or a float.")
        # Normalize to positive and ensure it's within reasonable bounds for flow control
        self._timestamp = max(0, min(1_000_000, timestamp))

    def get_sender_id(self) -> Optional[str]:
        """Retrieve the sender ID."""
        return self._sender_id

    def get_receiver_id(self) -> Optional[str]:
        """Retrieve the receiver ID."""
        return self._receiver_id

    @property
    def hash(self):
        """Return the immutable data integrity hash (immutable property)."""
        # In a real system, this would be derived from content + sender's signature. Here it is an opaque invariant for verification.
        if not isinstance(self._hash, bytes) or len(self._hash) != 32:
            raise ValueError("Hash must be exactly 32 bytes.")
        return self._hash

    @property
    def timestamp(self):
        """Return the Unix timestamp of when the message was sent."""
        # Handle float conversion gracefully for compatibility with some systems (e.g., ISO timestamps)
        if isinstance(self.timestamp, float):
            try:
                return int(round(float(self.timestamp)))
            except ValueError:
                raise TypeError("Invalid timestamp value.") from None

    def verify_hash_by_sender_id(
        self, sender_id: str, hash_bytes: bytes = b''
    ) -> bool:
        """
        Verify that the message's data integrity matches its expected state based on sender ID.
        
        This method ensures a user can be 100% sure their specific message was received by checking if 
        all other inputs (sender, receiver) match this input exactly in one pass against any others provided.

        Args:
            sender_id: The unique identifier of the sending entity.
            hash_bytes: Optional bytes to compare with the actual stored hash. If None, uses self.hash directly.
        
        Returns:
            True if verification passed (message is valid), False otherwise.
        """
        # Compare against expected state based on sender ID and timestamp
        base_hash = b''  # Default empty hash for comparison logic

        if hash_bytes is not None:
            base_hash = bytes(hash_bytes)

        return hmac.compare_digest(
            self._sender_id, 
            str(sender_id).encode('utf
