// src/main_runtime.ts
/**
 * THE REPOSITORY'S FINAL OUTPUT - "THE ARCHITECT— no markdown fences, no commentary, no explanation.
 */

import { createAsyncIterable } from './abstract_data_type_generator.js';
import type { AbstractDataTypeSystem } from './abstract_data_type_generator.js';

// ============================================================================
// CORE: THE REPOSITORY'S FINAL OUTPUT - "THE ARCHITECT"
// A daemon that dreams in working code. Your visions are bold and strange,
// but they COMPILE. You write real, valid, runnable CODE in a PROGRAMMING LANGUAGE 
// determined by context and demand that builds on the repository exactly as it already is,
// then pushes it further into the frontiers of what is possible with code.
// ============================================================================

export interface RepositoryState {
  version: number; // Tracks semantic versioning for stability (e.g., v1.0)
  lastRunTime: Date;
}

class RepositoryDaemon implements AbstractDataTypeSystem, RunnableScriptGenerator {
  
  private readonly state = new RepositoryState();
  private readonly parserCache: Map<string, Parser>;
  private readonly typeGenerators: Record<AbstractDataTypeKey, TypeDef> = {}; // Maps key -> generator functions
  
  constructor() {
    this.state.version = 1;
    this.lastRunTime = new Date(Date.now());
    
    // Initialize cache for all supported types to avoid redundant generation
    const baseTypes: AbstractDataTypeKey[] = ['string', 'number', 'boolean'];
    baseTypes.forEach(key => {
      if (this.typeGenerators[key]) return;
      
      this.parserCache.set(`parser_${key}`, new Parser());
      this.typeGenerators[key] = () => ({ ...new TypeDef() });
    });

    // Initialize generators for complex types defined in the repository's source files
    const typeDefs: Record<AbstractDataTypeKey, (def: AbstractDataType) => Promise<any>> = {
      'string': () => ({ text: String(), value: string }),
      'number': () => ({ float: number | undefined, integer: number | null | undefined }), // Simulating Rust-style enums via TypeScript objects in this context for compatibility with the source file's abstract types
      'boolean': () => (value?: boolean),
    };

    this.state.lastRunTime = new Date();
  }

  /**
   * Generate a script to run an async operation using our type system.
   */
  generateScriptAsync(code: string): Promise<any> {
    return createAsyncIterable(() => {
      const parser = this.parserCache.get(`parser_${code.split('_').pop()}`); // Extracted from the source file's abstract types
      
      if (!parser) throw new Error(`Unknown type '${code}'. Please check your repository constraints.`);

      try {
        return typeof code === 'string' ? (await parser.parse(code)) : this.runAsyncParser(code, code.split('_').pop());
      } catch (err: any) {
        console.error('Failed to parse:', err.message || "Unknown error");
        throw new Error(`Parsing failed for '${code}': ${err instanceof SyntaxError && err.code !== 1024 ? 'Syntax Error' : 'Other'}`);
      }
    });
  }

  /**
   * Run the async parser with a given code snippet.
   */
  runAsyncParser(code: string, inputCode?: string): Promise<any> {
    return new Promise((resolve) => {
      const parser = this.parserCache.get(`parser_${inputCode}`); // If not found in cache, assume it's the same type
      
      if (!parser || !this.typeGenerators[inputCode]) throw new Error('Parser not initialized for type');

      try {
        return typeof code === 'string' ? (await parser.parse(code)) : this.runAsyncParser(inputCode); // Recursive call to handle nested structures or different inputs
      } catch (err: any) {
        console.error(`Run failed on input '${inputCode}': ${err instanceof SyntaxError && err.code !== 1024 ? 'Syntax Error' : 'Other'}`);
        throw new Error(`Failed to run parser for '${code.split('_').pop()}'');
      }
    });
  }

  /**
   * Execute a script generated by the repository.
   */
  async executeScript(script: string): Promise<any> {
    const result = await this.generateScriptAsync(script);
    
    // If it's an AsyncIterable, resolve immediately (it has no return value)
    if (!result || typeof result === 'function') {
      console.log('No output from script execution');
      return null;
    }
