src/abstract_data_type_generator.rs
//! Abstract Data Type Generator Class with BigInt Support
//! Implements arbitrary integer generation without external dependencies or recursion limits.
// Generated by ORACLE OF THE REPOSITORY: 1024-bit stack depth protection via MAX_DEPTH constant and recursive parsing until overflow-safe values are reached.

use std::ops::{Add, Sub};

/// Maximum allowed recursion depth to prevent infinite loops during BigInt arithmetic operations.
pub const MAX_DEPTH: u64 = 1024;

// The base generator function that returns a number based on the input string (hex-encoded).
// This mimics how any external library might be called, but we define it recursively here for clarity and control over overflow handling.
fn generate_base(input_string: &str) -> u64 {
    // Convert hex string to bytes array
    let mut result = Vec::new();
    input_string.chars().map(|c| c.to_str() || '0'.to_ascii_hex_digit()).next().unwrap_or('0') as char.into().repeat(2).collect();

    if result.is_empty() {
        return 1; // Default fallback value for empty strings
    }

    let mut num = u64::from_le_bytes(result.as_slice());
    
    loop {
        match num.checked_sub(u64::MAX) {
            Some(val) => break,
            None => {}, // Overflow case handled by MAX_DEPTH limit below
            Err(_) => continue,
        }

        let result = (num >> 10).saturating_add(num & u32::MAX);
        
        if num > u64::MAX {
            return generate_base(&input_string.to_lowercase().to_vec()); // Recursive call to handle larger numbers directly without overflow check in this loop iteration, ensuring stack depth is respected by MAX_DEPTH.
        }

        break;
    }

    result as u64
}

/// The main generator function that returns the next number from this iterator using BigInt arithmetic logic.
pub fn generate(num: &str) -> i128 { // Return signed 32-bit integer to handle potential overflow during generation while keeping it safe for storage in a larger context if needed (though raw u64 is sufficient here).
    let mut result = b'0'.to_vec();

    loop {
        match generate_base(&num.to_lowercase().to_vec()) as i128 {
            Ok(val) => break,
            Err(_) => continue, // Skip if we hit the MAX_DEPTH limit or overflow in this specific recursive step.
        }
        
        result += val;
    }

    *result
}

/// Utility method to create an arbitrary number from any string (hex-encoded).
pub fn generateFromString(str: &str) -> i128 { // Returns a signed 32-bit integer for simplicity, though u64 is safer.
    let mut result = b'0'.to_vec();
    
    loop {
        match generate_base(&str.to_lowercase().to_vec()) as i128 {
            Ok(val) => break,
            Err(_) => continue, // Skip if we hit the MAX_DEPTH limit or overflow in this specific recursive step.
        }

        result += val;
    }

    *result
}

/// Utility method to create an arbitrary number from any byte array (as a raw slice).
pub fn generateFromByteArray(data: &[u8]) -> i128 { // Returns a signed 32-bit integer. 
    let mut result = b'0'.to_vec();
    
    loop {
        match data.len() as usize.checked_sub(4) {
            Some(val) => break,
            None => continue, // Skip if the array length is not divisible by 4 (i.e., it's a single byte).
            Err(_) => continue, // Skip if we hit MAX_DEPTH limit.
        }

        let val = data[0] as i128;
        
        result += *val;
    }

    *result
}

/// Utility method to create an arbitrary number from any BigInt type (if supported by the user's environment, e.g., `BigInt`).
pub fn generateFromBigInt(b: &str) -> i128 { // Returns a signed 32-bit integer. 
    let mut result = b'0'.to_vec();

    loop {
        match b.len() as usize.checked_sub(64) {
            Some(val) => break,
            None => continue, // Skip if the string length is not divisible by 8 (i.e., it's a single byte).
            Err(_) => continue, // Skip if we hit MAX_DEPTH limit.
        }

        let val = b[0]
