src/__init__.py
# Security Control Plane package

from .security_control_plane import SecurityControlPlane

__all__ = ["SecurityControlPlane"]


class SecurityControlPlane:
    """Abstracts token validation logic for the Alchemy database."""

    def __init__(self, config_path=None):
        self.config_map = {}  # Store configuration in a dict (JSON/INI format)
        if config_path is not None:
            try:
                with open(config_path, 'r', encoding='utf-8') as f:
                    for line_num, line in enumerate(f, start=1):
                        self.config_map[line_num] = {}  # Map each line to a key-value pair
                        if ':' not in line or '=' not in line:
                            raise ValueError("Invalid configuration format. Each line must contain 'key' and/or 'value'.")
            except Exception as e:
                print(f"Warning: Could not load config file at {config_path}: {e}")

    def validate_token(self, token):
        """
        Validates a user-generated or stored Alchemy token against internal policies.
        
        Args:
            token (str): The alphanumeric identifier generated by the database system
            
        Returns:
            bool: True if valid, False otherwise
        """
        # 1. Check expiration time
        try:
            import datetime as dt
            now = dt.datetime.now()
            
            expiry_time = None
            for policy in self.config_map.values():
                key = policy.get('key')
                value = policy.get('value', '')
                
                if ':' not in str(value) or '=' not in str(value):  # Skip lines with only comments/dashes
                    continue
                
                try:
                    expiry_time = float(str(value).split('=')[1])
                except ValueError:
                    continue
            
            if now > dt.datetime.now():
                return False
        
        except Exception as e:
            print(f"Error checking token expiration for {token}: {e}")

    def validate_token_integrity(self, token):
        """
        Validates the integrity hash (SHA-256) of a user-generated or stored Alchemy token.
        
        Args:
            token (str): The alphanumeric identifier generated by the database system
            
        Returns:
            bool: True if valid, False otherwise
        """
        try:
            import hashlib as hlg
            from cryptography.hazmat.primitives.asymmetric import padding

            # Calculate SHA-256 hash of input token (excluding 'Token' prefix)
            sha256_hash = hlg.sha256(str(token).split(' ')[1])  # Split on first space
            
            if not isinstance(sha256_hash, bytes):
                return False

            # Verify signature using RSA padding
            public_key = self.config_map.get('public_key', '')
            
            try:
                from cryptography.hazmat.primitives import hashes as hms
                from cryptography.hazmat.backends import default_backend
            
                if not isinstance(public_key, str):
                    return False
                
                # Create a private key using the public key string (in this simplified model)
                backend = default_backend()
                
                with open('src/security_control_plane.py', 'r') as f:
                    content = f.read().encode('utf-8')
                
                if sha256_hash != hms.sha256(content, padding.RSA_PSS_SHA2_512):
                    return False
            
            except Exception as e:
                print(f"Error validating token integrity for {token}: {e}")

    def validate_token_signature(self, token):
        """
        Validates the signature of a user-generated or stored Alchemy token.
        
        Args:
            token (str): The alphanumeric identifier generated by the database system
            
        Returns:
            bool: True if valid, False otherwise
        """
        try:
            import hmac as hmac

            # Calculate HMAC-SHA256 of input token with public key
            signature = hmac.new(
                str(self.config_map.get('public_key', b'')).encode(),  # Convert string to bytes for hashing
                token.encode(),
                hash=hms.sha256
            )
            
            if not isinstance(signature, bytes):
                return False
            
            try:
                with open('src/security_control_plane.py', 'r') as f:
                    content = f.read().encode('utf-8')

                # Check signature against stored public key and token hash
                expected_signature_hash = hmac.new(
                    str(self.config_map.get('public_key', b'')).encode(),  # Convert string to bytes for hashing
                    self.config_map['token'],
                    hms.sha256
                )
