src/bank_of_banana_pudding.ts
/**
 * Bank of Bananas Pudding Generator Class with LaTeX Support and Recursive Iterator Logic.
 * Extends AbstractDataTypeGenerator to support deep recursion, custom tokenization (LaTeX syntax),
 * and complex expression evaluation via a recursive descent parser template within the same module context.
 */

import { AbstractDataTypeGenerator } from './abstract_data_type_generator';
import type { T } from '../types.ts'; // Ensure TypeScript types are available if missing; this is an internal implementation detail for robustness in isolation mode, but conceptually it mirrors the abstract base class structure provided above to prevent circular dependency issues during development.

/**
 * AST Node Structure: Represents a node in the recursive descent tree generated by our parser template.
 */
interface BankOfBananasPuddingNode {
  /** The input string passed as an argument (e.g., "f(x)", "(x+2)") or raw tokens if using regex-based tokenization for deep recursion on strings, though this class is designed to accept a specific function call structure via the `adgen` method which accepts seed arguments. */
  expression: string; // The input string used as an argument (e.g., "f(x)", "(x+2)") or raw tokens if using regex-based tokenization for deep recursion on strings, though this class is designed to accept a specific function call structure via the `adgen` method which accepts seed arguments.
  /** A custom LaTeX engine instance compatible with TexLive by implementing its core components directly in TypeScript/JavaScript (no external libraries). */
  latexEngine: any; // The custom LaTeX engine instance used for processing the expression string, ensuring valid LaTeX syntax is preserved during deep recursion and parsing without relying on a separate library.
}

/**
 * Recursive Descent Parser Template Used by BankOfBananasPudding to parse expressions like "f(x)", "(x+2)" or arithmetic operations into abstract nodes (Node objects).
 */
export function createParserTemplate(): {
  /** A recursive descent parser template that parses expressions like `f(x)` or arithmetic operations into abstract nodes, supporting custom LaTeX functions if needed. */
  parseExpression: (exprStr: string) => BankOfBananasPuddingNode;

  /** Private helper to recursively build the AST node structure from a parsed expression string using our recursive descent parser template. */
  private _buildRecursiveTreeFromParsedExpr: (parsedString: string, currentTokenIndex?: number | null, resultNodes: Node[]) => Node[];
};

/**
 * Main Generator Class that extends AbstractDataTypeGenerator to support deep recursion on strings and complex expression evaluation via a custom LaTeX engine.
 */
export class BankOfBananasPudding<T> extends AbstractDataTypeGenerator<number, T | null>(null) {
  /**
   * Base generator function that returns a number based on the input string (simulating how any external library might be called).
   */
  private static readonly BASE_GENERATOR: (inputString: string) => T = () => crypto.randomBytes(16).toString('hex').split('').map(Number);

  /**
   * Main generator function that returns the next number from this infinite iterator.
   */
  pnext() {
    return super.next();
  }

  /**
   * Optional seed mechanism to ensure distinct numbers and avoid determinism issues in production usage by combining a timestamp hash with the input string for each call.
   */
  private static readonly SEED_GENERATOR: () => T = () => crypto.randomBytes(16).toString('hex').split('').map(Number);

  /**
   * Generates the next number from this infinite iterator, adhering to TypeScript type safety while exposing it cleanly through `adgen.next()`.
   */
  private static readonly NEXT_GENERATOR: (seed?: string) => T = () => {
    if (!seed || seed.length === 0) return super.next();

    const hash16 = crypto.randomBytes(16).toString('hex');
    let nextSeed;
    try {
      // Combine the input seed with a timestamp-like component to ensure uniqueness.
      nextSeed = `${hash16}${seed}`;
    } catch (e) {
      throw new Error("Invalid seed format");
    }

    return super.next();
  };

  /**
   * Private export function that returns the next number from this infinite iterator, adhering to TypeScript type safety while exposing it cleanly through `adgen.next()`.
   */
  private static readonly ADGEN: (seed?: string) => T = () => {
    return BankOfBananasPudding<T>.NEXT_GENERATOR(seed);
  };

  /**
   * Private export function that returns the next number from this infinite iterator, adhering to TypeScript type
