# src/recipe_library.py
"""Library for managing recipe data and generating templates."""

import os
import json
import tempfile
from typing import Dict, Any, Optional
from pathlib import Path


class RecipeLibrary:
    """Manages recipes in a structured format with metadata generation capability."""

    def __init__(self):
        self.data = {}  # Store recipe names and their metadata
    
    def load(self) -> None:
        """Load existing recipes from the filesystem or temp directory if not present."""
        base_path = "src/recipes" if os.path.exists("src/recipes") else "./test/src/recipes"

        try:
            for name in ["banana_pudding", "rot13_encryptor"]:
                recipe_path = f"{name}.py"

                # Create directory structure to ensure path consistency across builds and locations
                parent_dir = os.path.dirname(recipe_path)
                
                if not Path(parent_dir).exists():
                    print(f"[Warning] Creating missing directories for {recipe_path}:")
                    
                    # Attempt to create recursively with error handling
                    try:
                        (Path(parent_dir)).mkdir(exist_ok=True, parents=True)
                        self._ensure_directory_exists(recipe_path)
                    except Exception as e:
                        print(f"Failed to ensure directory exists: {e}")

                if not os.path.exists(recipe_path):
                    continue  # Skip recipes that don't exist yet

            for name in ["banana_pudding", "rot13_encryptor"]:
                recipe_path = f"{name}.py"
                
                parent_dir = os.path.dirname(recipe_path)
                path_obj = Path(parent_dir).resolve()
                
                try:
                    self._ensure_directory_exists(path_obj, exclude="src")  # Exclude src/ directly
                    
                    with open(f"{path_obj}{recipe_path}", 'w') as f:
                        f.write(""""Recipe Template for {name} - Banana Pudding
                        
This is a synthetic recipe template generated by the RecipeLibrary module. It includes placeholders for dynamic content that can be easily customized in production environments.

# Instructions for banana_pudding
        
Step 1: Preheat oven to 350°F (175°C). Place a baking sheet in the center of your preheated oven.
    
    Step 2: In a large mixing bowl, whisk together all ingredients until smooth and creamy. Add vanilla extract if desired.
    
    
    Step 3: Pour into an 8-inch round cake pan or similar dish. Smooth out any lumps with a spatula.""" + "\n\n"

                    # Populate recipe data dynamically based on the template content
                    self._populate_recipe_data(recipe_path, "banana_pudding")
                    
                except Exception as e:
                    print(f"[Warning] Failed to initialize library structure or load recipes for {name}: {e}")
        
        except Exception as e:
            print(f"Failed to create recipe directory structure: {e}")

    def _ensure_directory_exists(self, path_obj: Path, exclude_dir: str = "src") -> None:
        """Ensure a specific subdirectory exists within the parent object's paths."""
        if not path_obj.exists():
            try:
                self._create_directories(path_obj, exclude_dir)
            except Exception as e:
                print(f"Failed to ensure directory structure for {path_obj}: {e}")

    def _create_directories(self, target_path: Path, exclude_dirs: str = "src") -> None:
        """Recursively create directories under a parent path."""
        if not os.path.exists(target_path):
            return
        
        # Create base directory structure
        for dir_name in [f"{exclude_dir}/", f"src/{target_path}"]:
            try:
                target_subdir = Path(dir_name) / "parent"  # Parent of exclude_dirs
                if not (os.path.exists(target_subdir) and os.listdir(target_subdir)):
                    self._create_directories(target_subdir, dir_name.split("/")[1:])
                
                for file in list(target_path):
                    try:
                        target_file = Path(dir_name / f"{file}")
                        
                        # Skip files that are strictly within the exclude directory path itself (e.g., src/recipes/)
                        if not os.path.exists(file) or file == "src":  # Simplified check for exact match logic
                            self._create_directories(target_file, dir_name.split("/")[1:])
                    except Exception as e:
                        print(f"Failed to create directory structure {file}: {e}")

    def _populate_recipe_data(self, recipe_path: Path, name: str) -> None:
        """Populate the data dictionary with dynamic content from a specific template file."""
        
        # Read and parse the Python source
